<h3>Add Admin page</h3>

<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form); //<form method="post">
?>
<div class="form-group">
    <?= $this->formElement($form->get('login')); ?>
</div>
<div class="form-group">
    <?= $this->formElement($form->get('password')); ?>
</div>
<?= $this->formElement($form->get('csrf')); ?>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag();?>
