<div class="row">
    <h1 class="text text-primary col-lg-3 col-md-4 col-xs-12">Pokemons list</h1>
</div>
<div class="row">
    <a href="<?= $this->url('admin_home/admin_pokemon_create') ?>" class="btn btn-primary btn-lg pull-right" name="button">Ajouter un pokemon <span class="glyphicon glyphicon-plus"></span></a>
</div>
<?php if ( (bool) count($this->messages) ) : ?>
<div class="row alert alert-info">
    <?php foreach ($this->messages as $msg): ?>
    <p class="col-xs-10 col-xs-offset-1"><strong><?= $msg ?></strong></p>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php if ( (bool) count($this->pokemons) ) : ?>
<div style="margin-top: 40px" class="row">
    <table class="table table-condenses table-hover">
        <thead>
            <tr>
                <th>national ID</th>
                <th>Name</th>
                <th>Image</th>
                <th>Evolutions</th>
                <th>Types</th>
                <th>Show</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->pokemons as $poke): ?>
            <?php
                $idnation = (string) $poke->getIdNational();
                while (strlen($idnation) < 3) {
                    $idnation = "0".$idnation;
                }
            ?>
            <tr id="poke-<?= $poke->getIdNational() ?>">
                <td><?= "#".$idnation ?></td>
                <td><?= $poke->getName() ?></td>
                <td><img src="<?= $poke->getImage() ?>" alt="<?= $poke->getName() ?> image"></td>
                <td>
                <?php if ( is_array($poke->getEvolutions()) ) : ?>
                    <div class="evolutions row">
                    <?php foreach ($poke->getEvolutions() as $evo): ?>
                        <a href="#poke-<?= $evo->getIdNational() ?>"><?= $evo->getName() ?></a>
                        <?php if ( is_array($evo->getEvolutions()) ) : ?>
                            <div class="next-evolutions">
                            <?php foreach ($evo->getEvolutions() as $next_evo): ?>
                                <a href="#poke-<?= $next_evo->getIdNational() ?>"><?= $next_evo->getName() ?></a>
                            <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                </td>
                <td>
                    <?php if ( $poke->getType1() == null && $poke->getType2() == null ) : ?>
                        None
                    <?php else: ?>
                        <?php if ( $poke->getType1() != null ) : ?>
                        <span style="color: <?= $poke->getType1()['color']; ?>;"><?= $poke->getType1()['nom_type']; ?></span>
                        <?php endif; ?>
                        <?php if ( $poke->getType2() != null ) : ?>
                        <span style="color: <?= $poke->getType2()['color']; ?>;"><?= $poke->getType2()['nom_type']; ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
                <td><a href="/admin/pokemon/show/<?= $poke->getIdNational() ?>"><button type="button" class="btn btn-success btn-xs">Show</button></a></td>
                <td><a href="/admin/pokemon/edit/<?= $poke->getIdNational() ?>"><button type="button" class="btn btn-warning btn-xs">Edit</button></a></td>
                <td><a href="/admin/pokemon/delete/<?= $poke->getIdNational() ?>"><button type="button" class="btn btn-danger btn-xs">Remove</button></a></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
    echo $this->paginationControl(
      $this->pokemons,
      'Sliding',
      'partial/pagination',
      ['route' => 'admin_home/paged']
    );
?>
<?php endif; ?>
