<h3>Admin Login</h3>
<?php if ( (bool) count($this->messages) ): ?>
    <div class="messages">
    <?php foreach ($this->messages as $message):?>
        <p class="text text-error"><?= $message ?></p>
    <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form); //<form method="post">
?>
<div class="form-group">
    <?= $this->formElement($form->get('login')); ?>
</div>
<div class="form-group">
    <?= $this->formElement($form->get('password')); ?>
</div>
<?= $this->formElement($form->get('csrf')); ?>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag();?>
