<?php if ( $this->pokemon != null ) : ?>
<?php $poke = $this->pokemon; ?>
<?php
    $idnation = (string) $poke->getIdNational();
    while (strlen($idnation) < 3) {
        $idnation = "0".$idnation;
    }
?>
<div class="row">
    <img class="height-auto col-lg-1 col-md-1 col-xs-2" src="<?= $poke->getImage() ?>" alt="<?= $poke->getName() ?>">
    <h1 class="text text-primary col-lg-4 col-md-6 col-xs-8"><?= $poke->getName() ?> details</h1>
</div>
<div class="row light-top-margin">
    <p class="text text-info title-3 col-xs-offset-1">Description</p>
    <p class="text col-xs-offset-1 light-top-margin"><?= $poke->getDescription() ?></p>
</div>
<div class="row light-top-margin">
    <p class="text text-info title-3 col-xs-offset-1">National ID</p>
    <p class="text col-xs-offset-1 light-top-margin"><?= $poke->getIdNational() ?></p>
</div>
<div class="row light-top-margin">
    <p class="text text-info title-3 col-xs-offset-1">Types</p>
    <?php if ($poke->getType1() != null): ?>
    <div class="col-xs-offset-1 col-xs-6 display-flex-row justify-start">
        <p class="admin-show-type-label label title-4" style="background: <?= $poke->getType1()->getColor() ?>"><?= $poke->getType1()->getNameType() ?></p>
        <?php if ($poke->getType2() != null): ?>
        <p id="admin-show-type-2-label" class="admin-show-type-label label title-4" style="background: <?= $poke->getType2()->getColor() ?>"><?= $poke->getType2()->getNameType() ?></p>
        <?php endif; ?>
    </div>
    <?php endif; ?>
</div>
<div class="row light-top-margin display-flex-column">
    <p class="text text-info title-3">Tree evolution</p>
    <div class="row light-top-margin display-flex-row space-around">
        <?php if ($poke->getParent() != null) : ?>
        <?php $parent = $poke->getParent(); ?>
            <?php if ( $parent->getParent() != null): ?>
            <?php $deepParent = $parent->getParent(); ?>
                <div class="pokemon-detail-tree-container display-flex-row space-around">
                    <a href="<?= $this->basePath('/admin/pokemon/show/'.$deepParent->getIdPokemon()); ?>">
                        <img style="max-width: 85px;" class="full-width height-auto" src="<?= $deepParent->getImage() ?>" alt="<?= $deepParent->getName() ?> image">
                    </a>
                    <span class="glyphicon text-primary text-lg glyphicon-arrow-right title-1"></span>
                </div>
            <?php endif; ?>
            <div class="pokemon-detail-tree-container display-flex-row space-around">
                <a href="<?= $this->basePath('/admin/pokemon/show/'.$parent->getIdPokemon()); ?>">
                    <img style="max-width: 85px;" class="full-width height-auto" src="<?= $parent->getImage() ?>" alt="<?= $parent->getName() ?> image">
                </a>
                <span class="glyphicon text-primary text-lg glyphicon-arrow-right title-1"></span>
            </div>
        <?php endif; ?>
        <div class="admin-show-evolution-group display-flex-column space-around">
            <div class="pokemon-detail-tree-container active display-flex-row space-around">
                <a disabled>
                    <img style="max-width: 85px;" class="full-width height-auto" src="<?= $poke->getImage() ?>" alt="<?= $poke->getName() ?> image">
                </a>
                <span class="glyphicon text-primary text-lg glyphicon-arrow-right title-1"></span>
            </div>
        </div>
        <?php if ( $poke->getEvolutions() != null ): ?>
        <?php $first_evolutions = $poke->getEvolutions(); ?>
            <?php $deppest_evolutions = []; ?>
            <div class="admin-show-evolution-group display-flex-column space-around">
            <?php foreach ($first_evolutions as $first_evo): ?>
                <?php
                    if ( $first_evo->getEvolutions() != null ){
                        foreach ($first_evo->getEvolutions() as $final_evo) {
                            $deppest_evolutions[] = $final_evo;
                        }
                    }
                ?>
                <div class="pokemon-detail-tree-container display-flex-row space-around">
                    <a href="<?= $this->basePath('/admin/pokemon/show/'.$first_evo->getIdPokemon()); ?>">
                        <img style="max-width: 85px;" class="full-width height-auto" src="<?= $first_evo->getImage() ?>" alt="<?= $first_evo->getName() ?> image">
                    </a>
                    <span class="glyphicon text-primary text-lg glyphicon-arrow-right title-1"></span>
                </div>
            <?php endforeach; ?>
            </div>
            <?php if (count($deppest_evolutions) > 0 ): ?>
            <div class="admin-show-evolution-group display-flex-column space-around">
            <?php foreach ($deppest_evolutions as $final_evo): ?>
                <div class="pokemon-detail-tree-container display-flex-row space-around">
                    <a href="<?= $this->basePath('/admin/pokemon/show/'.$final_evo->getIdPokemon()); ?>">
                        <img style="max-width: 85px;" class="full-width height-auto" src="<?= $final_evo->getImage() ?>" alt="<?= $final_evo->getName() ?> image">
                    </a>
                    <span class="glyphicon text-primary text-lg glyphicon-arrow-right title-1"></span>
                </div>
            <?php endforeach; ?>
            </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
<?php else : ?>
<div class="row">
    <h1 class="text text-primary">No pokemon matched</h1>
</div>
<?php endif; ?>
