<?php if ( $this->pokemon != null ) :?>
    <?php $poke = $this->pokemon;?>
    <div class="row">
        <h1 class="text text-primary col-lg-4 col-md-4 col-xs-8">Mise à jour - <?= $poke->getName(); ?></h1>
        <img src="<?= $poke->getImage(); ?>" alt="image <?= $poke->getName(); ?>" class="img-responsive col-lg-1 col-xs-2">
    </div>

    <?php
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form); //<form method="post">
    ?>
    <div class="form-group">
        <?= $this->formRow($form->get('name')->setValue($poke->getName())); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($form->get('image')); ?>
    </div>
    <div class="form-group">
    <?php
        if ($form->has('id_parent')) {
            echo $this->formRow($form->get('id_parent'));
        }
    ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($form->get('description')->setValue($poke->getDescription())); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($form->get('type1')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($form->get('type2')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($form->get('id_national')->setValue($poke->getIdNational())); ?>
    </div>
    <?= $this->formHidden($form->get('csrf')); ?>
    <?= $this->formHidden($form->get('id_pokemon')->setValue($poke->getIdPokemon())); ?>
    <?= $this->formSubmit($form->get('submit')); ?>
    <?= $this->form()->closeTag();?>
<?php else: ?>
    <div class="row light-top-margin">
      <h1 class="text text-primary">Pokémon inexistant</h1>
    </div>
<?php endif; ?>
