<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Pokedex App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ?>
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/reset.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/index-wrapper.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/map-wrapper.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/card.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/size.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/modules/animate.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/modules/display.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/modules/size.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/modules/margin.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/modules/text.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/modules/position.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/navbar.css" type="text/css" media="screen, projection">
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCg4RtnNrFMj-kDzssqzfICe4XPJGa1d1A"></script>
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/global.css" type="text/css" media="screen, projection">
    </head>
    <body>
        <div id="pokedexApp" class="full-height"></div>
    </body>
    <script type="text/javascript" src="<?= $this->basePath() ?>/dist/js/pokedex.js"></script>
</html>
