<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Pokedex Admin App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                'rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ])
            ->prependStylesheet($this->basePath('css/modules/size.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <?= $this->headScript()
            ->prependFile($this->basePath('admin_js/bootstrap.min.js'))
            ->prependFile($this->basePath('admin_js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <?php $user = $_SESSION['identity']; ?>
    <body>
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="col-md-8">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?= $this->basePath('') ?>">
                            <img src="<?= $this->basePath('img/pokemon-logo.png') ?>" height="28" alt="Pokedex administration"/>
                        </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="<?= $this->url('admin_home') ?>">Admin</a></li>
                            <li><a href="<?= $this->url('admin_home') ?>">Add Pokemon</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                <?php if ( false != $user ): ?>
                    <div class="col-md-4 col-md-offset-6">
                        <span class="label label-info">
                            <?= $user; ?>
                        </span>
                    </div>
                    <div class="col-md-2">
                        <a href="<?php echo $this->url('admin_home/admin_logout') ?>" class="btn btn-danger">Logout</a>
                    </div>
                <?php else: ?>
                    <div class="col-md-2 col-md-offset-10">
                        <a href="<?php echo $this->url('admin_home/admin_login') ?>" class="btn btn-primary">Login</a>
                    </div>
                <?php endif; ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
        </div>
    </body>
</html>
