<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Pokedex App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ?>
        <link rel="stylesheet" href="<?= $this->basePath() ?>/css/reset.css" type="text/css" media="screen, projection">
    </head>
    <body>
        <div id="pokedexApp"></div>
    </body>
    <script type="text/javascript" src="<?= $this->basePath() ?>/dist/js/pokedex.js"></script>
</html>
