<?php
    $post = $this->post;
    $postedAt = $this->dateFormat(
        $post->getCreated(),
        IntlDateFormatter::MEDIUM,
        IntlDateFormatter::MEDIUM,
        'en_US'
    );
?>
<h1><?= $this->escapeHtml($post->getTitle()); ?></h1>
<a class="btn btn-primary" href="<?= $this->url('edit_post', ['postId' => $post->getId()]); ?>">
  <span class="glyphicon glyphicon-pencil"></span> Delete
</a>
<a class="btn btn-danger" href="<?= $this->url('delete_post', ['postId' => $post->getId()]); ?>">
  <span class="glyphicon glyphicon-remove"></span> Delete
</a>
<div class="row">
  <div class="col-md-12">
    <?= nl2br($this->escapeHtml($post->getContent())); ?>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-12">
    Date: <?= $postedAt; ?>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-12">
    Category: <?= $post->getCategory()->getName(); ?>
  </div>
</div>
