<h1>New user</h1>

<?php
  $form = $this->form;
  $form->prepare();
  echo $this->form()->openTag($form); // <form>

?>

<div class="form-group">
  <?= $this->formRow($form->get('firstName')); ?>
</div>
<div class="form-group">
  <?= $this->formRow($form->get('lastName')); ?>
</div>
<div class="form-group">
  <?= $this->formRow($form->get('email')); ?>
</div>
<div class="form-group">
  <?= $this->formRow($form->get('password')); ?>
</div>
<div class="form-group">
  <?= $this->formRow($form->get('repeatPassword')); ?>
</div>
<?= $this->formRow($form->get('submit')); ?>
<?= $this->form()->closeTag(); // </form> ?>
